<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit484796a89f3acd6e2fca6b61216d732a
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Leafo\\ScssPhp\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Leafo\\ScssPhp\\' => 
        array (
            0 => __DIR__ . '/..' . '/leafo/scssphp/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit484796a89f3acd6e2fca6b61216d732a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit484796a89f3acd6e2fca6b61216d732a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit484796a89f3acd6e2fca6b61216d732a::$classMap;

        }, null, ClassLoader::class);
    }
}
